In [15]:
# import pandas as pd

# # Run this to create the 'employees.csv' file locally
# data = {
#     'Employee_ID': [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
#     'Name': ['John Doe', 'Jane Smith', 'Michael Brown', 'Emily Davis', 'James Wilson', 'Sarah Martinez', 'David Anderson', 'Chris Taylor', 'Amanda Thomas', 'Robert Jackson'],
#     'Department': ['Sales', 'Engineering', 'Marketing', 'Engineering', 'Sales', 'HR', 'Marketing', 'Engineering', 'HR', 'Sales'],
#     'Salary': [65000, 95000, 54000, 88000, 62000, 50000, 58000, 105000, 52000, 71000],
#     'Join_Date': ['2022-03-15', '2021-06-01', '2023-01-10', '2020-11-20', '2022-08-05', '2024-02-14', '2021-09-18', '2019-04-12', '2023-07-22', '2020-05-30'],
#     'Performance_Score': ['Excellent', 'Excellent', 'Good', 'Outstanding', 'Average', 'Good', 'Average', 'Outstanding', 'Good', 'Excellent']
# }
# pd.DataFrame(data).to_csv('employees.csv', index=False)
# print("employees.csv file successfully created!")

In [16]:
import pandas as pd
df = pd.read_csv('employees.csv')

In [17]:
df

,Employee_ID,Name,Department,Salary,Join_Date,Performance_Score
0,101,John Doe,Sales,65000,2022-03-15,Excellent
1,102,Jane Smith,Engineering,95000,2021-06-01,Excellent
2,103,Michael Brown,Marketing,54000,2023-01-10,Good
3,104,Emily Davis,Engineering,88000,2020-11-20,Outstanding
4,105,James Wilson,Sales,62000,2022-08-05,Average
5,106,Sarah Martinez,HR,50000,2024-02-14,Good
6,107,David Anderson,Marketing,58000,2021-09-18,Average
7,108,Chris Taylor,Engineering,105000,2019-04-12,Outstanding
8,109,Amanda Thomas,HR,52000,2023-07-22,Good
9,110,Robert Jackson,Sales,71000,2020-05-30,Excellent

In [18]:
# Filtering based on one column
df["Department"] = df["Department"].str.lower()

In [19]:
df

,Employee_ID,Name,Department,Salary,Join_Date,Performance_Score
0,101,John Doe,sales,65000,2022-03-15,Excellent
1,102,Jane Smith,engineering,95000,2021-06-01,Excellent
2,103,Michael Brown,marketing,54000,2023-01-10,Good
3,104,Emily Davis,engineering,88000,2020-11-20,Outstanding
4,105,James Wilson,sales,62000,2022-08-05,Average
5,106,Sarah Martinez,hr,50000,2024-02-14,Good
6,107,David Anderson,marketing,58000,2021-09-18,Average
7,108,Chris Taylor,engineering,105000,2019-04-12,Outstanding
8,109,Amanda Thomas,hr,52000,2023-07-22,Good
9,110,Robert Jackson,sales,71000,2020-05-30,Excellent

In [20]:
# Filtering based on multiple columns
df.iloc[(df["Department"] == 'Sales') & (df["Salary"]>63000)]

Empty DataFrame
Columns: [Employee_ID, Name, Department, Salary, Join_Date, Performance_Score]
Index: []

In [21]:
# Updating values based on single column
df.loc[df["Employee_ID"] == 109, "Department"] = "Head Operations"

In [22]:
df.loc[df["Employee_ID"] == 109, "Department"]

8    Head Operations
Name: Department, dtype: str

In [23]:
df.loc[1:3]

,Employee_ID,Name,Department,Salary,Join_Date,Performance_Score
1,102,Jane Smith,engineering,95000,2021-06-01,Excellent
2,103,Michael Brown,marketing,54000,2023-01-10,Good
3,104,Emily Davis,engineering,88000,2020-11-20,Outstanding

In [24]:
df.loc[df["Employee_ID"] == 109, ["Department","Salary"]]

        Department  Salary
8  Head Operations   52000

In [28]:
df[(df["Employee_ID"] > 25) & (df["Salary"] > 50000)]

,Employee_ID,Name,Department,Salary,Join_Date,Performance_Score
0,101,John Doe,sales,65000,2022-03-15,Excellent
1,102,Jane Smith,engineering,95000,2021-06-01,Excellent
2,103,Michael Brown,marketing,54000,2023-01-10,Good
3,104,Emily Davis,engineering,88000,2020-11-20,Outstanding
4,105,James Wilson,sales,62000,2022-08-05,Average
6,107,David Anderson,marketing,58000,2021-09-18,Average
7,108,Chris Taylor,engineering,105000,2019-04-12,Outstanding
8,109,Amanda Thomas,Head Operations,52000,2023-07-22,Good
9,110,Robert Jackson,sales,71000,2020-05-30,Excellent

In [26]:
df

,Employee_ID,Name,Department,Salary,Join_Date,Performance_Score
0,101,John Doe,sales,65000,2022-03-15,Excellent
1,102,Jane Smith,engineering,95000,2021-06-01,Excellent
2,103,Michael Brown,marketing,54000,2023-01-10,Good
3,104,Emily Davis,engineering,88000,2020-11-20,Outstanding
4,105,James Wilson,sales,62000,2022-08-05,Average
5,106,Sarah Martinez,hr,50000,2024-02-14,Good
6,107,David Anderson,marketing,58000,2021-09-18,Average
7,108,Chris Taylor,engineering,105000,2019-04-12,Outstanding
8,109,Amanda Thomas,Head Operations,52000,2023-07-22,Good
9,110,Robert Jackson,sales,71000,2020-05-30,Excellent

In [ ]:
print(True+True)

2